// <auto-generated />
namespace VAMK.FWMS.DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class v : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v));
        
        string IMigrationMetadata.Id
        {
            get { return "202503202028067_v"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
