// <auto-generated />
namespace JitSys.DataObjects.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _1809201658AS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_1809201658AS));
        
        string IMigrationMetadata.Id
        {
            get { return "201809201128397_1809201658AS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
