namespace VAMK.FWMS.Models.Enums
{
    public enum EmailTemplate
    {
        IOU_PENDING_LEAD_APPROVAL = 1,
        IOU_PENDING_HOD_APPROVAL = 2,
        IOU_FINANCE_APPROVED = 3,
        IOU_REJECTED = 4,
        PETTY_CASH_PENDING_LEAD_APPROVAL = 5,
        PETTY_CASH_PENDING_HOD_APPROVAL = 6,
        PETTY_CASH_FINANCE_APPROVED = 7,
        PETTY_CASH_REJECTED = 8,
        EMPLOYEE_REGISTRATION = 9,
        PETTY_CASH_CANCELLATION = 10,
        MEDICAL_CLAIM_PENDING_HR_CHECK = 11,
        MEDICAL_CLAIM_PENDING_HR_APPROVAL = 12,
        MEDICAL_CLAIM_REJECTED = 13,
        MEDICAL_CLAIM_PENDING_FINANCE_APPROVED = 14,
        MEDICAL_CLAIM_CANCELLATION = 15,
        MEDICAL_CLAIM_FINANCE_APPROVED = 16,
    }
}
